import { Inter } from '@next/font/google';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import { Client } from '../../belShare/ts-client';
import { DirectSecp256k1HdWallet } from '@cosmjs/proto-signing';
import Form from '../components/Form';
import Profile from '../components/Profile/Profile';
const inter = Inter({ subsets: ['latin'] });

const Wallet = (props) => {
	const [tx, setTx] = useState(null);
	const [client, setClient] = useState(null);
	const [balances, setBalances] = useState(null);
	const [wallet, setWallet] = useState(null);

	useEffect(() => {
		(async () => {
			const mnemonic =
				'unaware surface excess job post avoid river screen decide change strategy glow faculty retire odor seven will camera dwarf border wool little cupboard place';

			const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic, { prefix: 'share' });

			const chain = new Client(
				{
					apiURL: 'http://localhost:1317',
					rpcURL: 'http://localhost:26657',
					prefix: 'share',
				},
				wallet
			);
			setClient(chain);
			const accounts = await wallet.getAccounts();
			setWallet(accounts[0]);
			const balance = await chain.CosmosBankV1Beta1.query.queryAllBalances(accounts[0].address);
			setBalances(balance.data.balances);
		})();
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				{wallet && <Profile client={client} wallet={wallet} />}
				<div className={styles.formGroup}>
					{/* <Form.Entity client={client} wallet={wallet} /> */}
					{/* <Form.Attribute client={client} wallet={wallet} /> */}
					<Form.User client={client} wallet={wallet} />
				</div>
			</main>
		</>
	);
};

export default Wallet;
